name            = Plugin Loader
description     = A thin application to implement a microkernel architecture.
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Plugin-Loader

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin
artifactId      = plugin-loader

archiveBaseName = Loader
